apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap
data:
  nginx_status.conf: |
    server {
        listen 80;
        server_name localhost;

        location /nginx_status {
              stub_status on;
              access_log  on;           
              allow all;  # REPLACE with your access policy
        }
    }
